[package]
name = "codelist"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
name = "codelist"
path = "src/lib.rs"
# Build as a dynamic library

[dependencies]
extendr-api = "0.8.0"
codelist-rs = { path = "../../rust/codelist-rs" }
